language: csharp
solution: "wsep192.sln"
mono: none
dotnet: 2.1.300
script:
  - dotnet restore
  - dotnet build
  - dotnet test tests/UnitTests/UnitTests.csproj
  - dotnet test tests/IntegrationTests/IntegrationTests.csproj
  - dotnet test tests/AcceptanceBridge/AcceptanceTests.csproj