dist: xenial
language: csharp
solution: Application/wsep192.sln
mono: none
dotnet: 2.2
script:
  - dotnet restore Application
  - dotnet build Application
  - dotnet test Application/tests/UnitTests/UnitTests.csproj
  - dotnet test Application/tests/IntegrationTests/IntegrationTests.csproj
  - dotnet test Application/tests/AcceptanceBridge/AcceptanceTests.csproj